module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],

  darkMode: 'media', // or 'media' or 'class'
  corePlugins: {
    float: false,
    clear: false,
    alignContent: false,
    alignSelf: false,
    flex: false,
    flexShrink: false,
    gridColumn: false,
    gridRow: false,
    gridAutoFlow: false,
    space: false,
    fontSmoothing: false,
    verticalAlign: false,
    whitespace: false,
    wordBreak: false,
    backgroundAttachment: false,
    backgroundOpacity: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderOpacity: false,
    divideWidth: false,
    divideColor: false,
    divideOpacity: false,
    borderCollapse: false,
    tableLayout: false,
    rotate: false,
    skew: false,
    resize: false,
    userSelect: false,
    strokeWidth: false,
  },
  theme: {
    screens: {
      tablet: "768px",
      desktop: "992px",
    },
    gridTemplateColumns: {
      1: "repeat(1, minmax(0, 1fr))",
      2: "repeat(2, minmax(0, 1fr))",
      3: "repeat(3, minmax(0, 1fr))",
      4: "repeat(4, minmax(0, 1fr))",
      5: "repeat(5, minmax(0, 1fr))",
    },
    placeholderColor: (theme) => theme("colors"),
    colors: {
      transparent: "transparent",
      white: "#ffffff",
      black: "#000000",
      "main-black": "#171717",
      "main-orange": "#FCA200",
      "main-orange-100": "#E19101",
      "main-orange-200": "#D28700",
      "dark-blue": "#23242E",
      gray: "#E3E3E3",
      "gray-100": "#F8F8F8",
      "gray-200": "#B7B7B7",
      "gray-300": "#EBEBEB",
      "gray-400": "#DBDBDB",
      "gray-500": "#ACACAC",
      "gray-600": "#dddddd",
      "gray-700": "#585965",
      "gray-800": "#888888",
      "gray-900": "#c4c4c4",
      "gray-1000": "#e3e3e3",
      "gray-1100": "#ececec",
      "gray-1200": "#D2D2D2",
      red: "#E63950",
    },
    fill: {
      white: "#ffffff",
      "main-black": "#171717",
      "main-orange": "#FCA200",
    },
    stroke: {
      "main-black": "#171717",
      "main-orange": "#FCA200",
    },
    spacing: {
      0: "0px",
      4: "4px",
      8: "8px",
      12: "12px",
      16: "16px",
      18: "18px",
      20: "20px",
      24: "24px",
      32: "32px",
      40: "40px",
      48: "48px",
      64: "64px",
      74: "74px",
      100: "100px",
      120: "120px",
    },
    fontFamily: {
      gilroy: ["Gilroy", "sans-serif"],
    },
    fontSize: {
      12: "12px",
      13: "13px",
      14: "14px",
      15: "15px",
      16: "16px",
      17: "17px",
      18: "18px",
      20: "20px",
      22: "22px",
      24: "24px",
      56: "56px",
      64: "64px",
    },
    lineHeight: {
      14: "14px",
      15: "15px",
      16: "16px",
      19: "19px",
      20: "20px",
      21: "21px",
      24: "24px",
      26: "26px",
      28: "28px",
      29: "29px",
      30: "30px",
      37: "37px",
      61: "61px",
      74: "74px",
    },
    fontWeight: {
      thin: 300,
      normal: 400,
      medium: 500,
      600: 600,
      bold: 800,
    },
    width: {
      48: "48px",
      59: "59px",
      118: "118px",
      auto: "auto",
      half: "50%",
      full: "100%",
      "max-content": "max-content",
      "fit-content": "fit-content",
    },
    minHeight: {
      // 140: '140px'
      48: "48px",
    },
    maxWidth: {
      auto: "auto",
      760: "760px",
      546: "546px",
      500: "500px",
      438: "438px",
      334: "334px",
    },
    minWidth: {
      // 8: '8px',
      59: "59px",
      48: "48px",
    },
    height: {
      48: "48px",
      59: "59px",
      screen: "100vh",
      full: "100%",
      auto: "auto",
      "max-content": "max-content",
    },
    borderRadius: {
      full: "9999px",
      circle: "50%",
      3: "3px",
    },
    borderWidth: {
      0: "0",
      1: "1px",
    },
    boxShadow: {
      none: "0",
      card: "0 0 15px 5px rgba(0, 0, 0, 0.25)",
    },
    inset: {
      "-135": "-135px",
      "-80": "-80px",
      "-29": "-29px",
      0: "0",
      auto: "auto",
      16: "16px",
      half: "50%",
      quarter: "25%",
    },

    gradientColorStops: (theme) => ({
      ...theme("colors"),
    }),
    zIndex: {
      0: "0",
      "-1": "-1",
      10: "10",
      20: "20",
    },
    letterSpacing: {
      6: "6%",
    },
  },
  extend: {
    gap: {
      20: "20px",
    },
  },
  variants: {
    zIndex: [],
    display: ["responsive"],
    objectFit: ["responsive"],
    objectPosition: ["responsive"],
    overflow: ["responsive"],
    position: ["responsive"],
    flexDirection: ["responsive"],
    flexWrap: ["responsive"],
    alignItems: ["responsive"],
    justifyContent: ["responsive"],
    order: ["responsive"],
    //Grid
    gridTemplateColumns: ["responsive"],
    gridColumnStart: ["responsive"],
    gridColumnEnd: ["responsive"],
    gridRowStart: ["responsive"],
    gridRowEnd: ["responsive"],
    gap: ["responsive"],
    //spacing
    padding: ["responsive"],
    margin: ["responsive", "hover"],
    width: ["responsive"],
    minWidth: ["responsive"],
    maxWidth: ["responsive"],
    height: ["responsive"],
    minHeight: ["responsive"],
    maxHeight: ["responsive"],
    //Fonts
    fontFamily: [],
    fontStyle: ["responsive"],
    textAlign: ["DEFAULT", "responsive"],
    textColor: ["hover", "focus", "group-hover", "responsive"],
    textDecoration: ["hover", "focus", "group-hover"],
    textTransform: [],
    backgroundColor: ["hover", "focus", "group-hover", "responsive"],
    gradientColorStops: ["active", "hover"],
    borderRadius: ["responsive"],
    borderWidth: ["DEFAULT", "hover", "focus", "responsive"],
    borderColor: [
      "hover",
      "focus",
      "group-hover",
      "responsive",
      "focus-within",
    ],
    boxShadow: ["hover", "responsive"],
    transitionProperty: ["hover"],
    transitionTimingFunction: ["hover"],
    translate: ["hover", "group-hover", "responsive"],
    cursor: ["DEFAULT"],
    outline: ["DEFAULT, hover, focus"],
    fill: ["hover", "focus", "group-hover"],
    stroke: ["hover", "focus", "group-hover"],
    accessibility: ["responsive"],
    placeholderColor: ["DEFAULT"],
    placeholderOpacity: ["DEFAULT"],
    leading: ["responsive"],
  },
  plugins: [],
};
